Repository ALaDyn/ALaDyn, pull requests merged in 2019-02, with the labels that each got.

#60 Add a second (fictional) pulse to symmetrize the ionized particles phase space
  src/ALaDyn.F90
  src/code_util.f90
  src/grid_and_particles.f90
  src/ionize.f90
  src/read_input.f90
Labels: enhancement, user-requested

#61 allow failures on travis for macos+mpich
  .travis.yml
Labels: build toolchain, continuous-integration, help wanted

#59 Fixed dump displacement for large buffers
  src/pic_dump.f90
Labels: bug, input-output

#63 Add logical flag to enable ionization for specific envelope pulse
  src/ALaDyn.F90
  src/code_util.f90
  src/ionize.f90
  src/pic_evolve_in_time.f90
  src/read_input.f90
Labels: enhancement

#65 Removed compilation warnings
  src/ALaDyn.F90
  src/grid_fields.f90
  src/ionize.f90
  src/parallel.F90
  src/particles.F90
  src/pdf_moments.f90
  src/pic_dump.f90
  src/pic_evolve_in_time.f90
  src/pic_in.f90
  src/pic_out.f90
  src/pic_out_util.f90
  src/pwfa_output_addons.f90
  src/util.f90
Labels: build toolchain, cleaning

#62 Modification to include the stretched grid in the envelope cycle
  src/all_param.f90
  src/code_util.f90
  src/grid_fields.f90
  src/grid_param.f90
  src/particles.F90
  src/pic_evolve_in_time.f90
  src/pic_in.f90
  src/pic_out_util.f90
Labels: enhancement

#70 Fixed undefined parameter in the envelope ionization
  src/ALaDyn.F90
  src/pic_evolve_in_time.f90
Labels: bug

#69 Improved fluid with a filter and with a Lax-Friedrichs flux
  src/ALaDyn.F90
  src/der_lib.f90
  src/grid_fields.f90
  src/parallel.F90
  src/particles.F90
  src/pic_evolve_in_time.f90
  src/pic_rutil.f90
Labels: enhancement

#72 Add some features to simulate the REMPI scheme
  src/ALaDyn.F90
  src/all_param.f90
  src/grid_and_particles.f90
  src/grid_fields.f90
  src/ionize.f90
  src/pic_in.f90
  src/read_input.f90
Labels: enhancement, user-requested

#74 Add debug compilation script for CNAF
  scripts/build/cmake.cnaf.gnu.debug
Labels: build toolchain, linux
